model:
  arch:
    n_blocks: 1
    n_front_share_blocks: 1
    n_front_share_wires: 1
    n_front_share_ops: 1
  sampler:
    strategy:
      n_diffs: 1


run:
  bsz: 28
  #  n_warm_epochs: 10
  n_epochs: 50

dataset:
  center_crop: 25
