model:
  arch:
    n_nodes: 2
    node_archs:
      - n_wires: 10
        encoder_op_list_name: 6x6_ryzxy
        n_blocks: 4
        n_layers_per_block: 2
        q_layer_name: u3cu3_0
      - n_wires: 10
        encoder_op_list_name: 10_ry
        n_blocks: 4
        n_layers_per_block: 2
        q_layer_name: u3cu3_0
    down_sample_kernel_size: 4
