model:
  name: super_qfc5
  arch:
    down_sample_kernel_size: 4
    encoder_op_list_name: 6x6_ryrz
    n_layers_per_block: 2
    q_layer_name: u3cu3_s0
    n_wires: 21
    output_remain: 20
    output_len: 10

dataset:
  n_train_samples: 20000

scheduler:
  name: cosine_warm

run:
  n_warm_epochs: 30
#  bsz: 32

callbacks:
  - callback: 'SubnetInferenceRunner'
    split: 'valid'
    subnet: 'largest'
    subcallbacks:
      - metrics: 'CategoricalAccuracy'
        name: 'superacc/largest_valid'
      - metrics: 'NLLError'
        name: 'superloss/largest_valid'
  - callback: 'MaxSaver'
    name: 'superacc/largest_valid'
  - callback: 'Saver'
    max_to_keep: 10
