dataset:
  name: mnist
  root: 'examples/data'
  train_valid_split_ratio: [0.9, 0.1]

criterion:
  name: nll

optimizer:
  name: adam
  lr: 1e-3
  weight_decay: 0.0

scheduler:
  name: cosine

run:
  n_epochs: 100
  bsz: 64
  workers_per_gpu: 8
  device: gpu

debug:
  pdb: False
  set_seed: True
  seed: 42

regularization:
  unitary_loss: False
  unitary_loss_lambda_trainable: False
  unitary_loss_lambda: 0

legalization:
  legalize: False
  epoch_interval: 9999999999
  step_interval: 9999999999
