dataset:
  name: mnist
  root: 'examples/data'
  train_valid_split_ratio: [0.9, 0.1]

criterion:
  name: nll

optimizer:
  name: adam
  lr: 5.0e-4
  weight_decay: 1.0e-4

scheduler:
  name: constant

run:
  n_epochs: 100
  bsz: 64
  workers_per_gpu: 8
  device: gpu

debug:
  pdb: False
  set_seed: False
  seed: 42
