dataset:
  name: mnist
  root: 'examples/data'
  train_valid_split_ratio: [0.9, 0.1]

model:
  name: q

criterion:
  name: nll

optimizer:
  name: adam
  lr: 5.0e-4
  weight_decay: 1.0e-4

scheduler:
  name: constant

n_epochs: 100
bsz: 64
workers_per_gpu: 8

pdb: False
device: gpu
