dataset:
  name: mnist
  root: 'examples/data'
  train_valid_split_ratio: [0.95, 0.05]
  center_crop: 28
  resize: 28
  binarize: False
  binarize_threshold: 0.1307
  digits_of_interest: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
  n_test_samples: null

criterion:
  name: nll

optimizer:
  name: adam
  lr: 5e-3
  weight_decay: 1.0e-4
  lambda_lr: 1.e-2

scheduler:
  name: cosine

trainer:
  name: q_trainer

run:
  n_epochs: 200
  bsz: 256
  workers_per_gpu: 8
  device: gpu

debug:
  pdb: False
  set_seed: True
  seed: 42

regularization:
  unitary_loss: False
  unitary_loss_lambda_trainable: False
  unitary_loss_lambda: 0

legalization:
  legalize: False
  epoch_interval: 9999999999
  step_interval: 9999999999

use_qiskit: False

callbacks:
  - callback: 'InferenceRunner'
    split: 'valid'
    subcallbacks:
      - metrics: 'CategoricalAccuracy'
        name: 'acc/valid'
  - callback: 'InferenceRunner'
    split: 'test'
    subcallbacks:
      - metrics: 'CategoricalAccuracy'
        name: 'acc/test'
  - callback: 'LegalInferenceRunner'
    split: 'valid'
    subcallbacks:
      - metrics: 'CategoricalAccuracy'
        name: 'acc_legal/valid'
  - callback: 'LegalInferenceRunner'
    split: 'test'
    subcallbacks:
      - metrics: 'CategoricalAccuracy'
        name: 'acc_legal/test'
  - callback: 'MaxSaver'
    name: 'acc/valid'

qiskit:
  use_qiskit: False
  use_real_qc: False
  apply_noise_model: False
  backend: null
