qiskit:
  optimization_level: 2

es:
  population_size: 100
  parent_size: 20
  mutation_size: 40
  mutation_prob: 0.5
  crossover_size: 40
  n_iterations: 40
  eval:
    use_noise_model: True
    use_real_qc: True
    bsz: qiskit_max
    n_test_samples: 150
