model:
  arch:
    sample_arch:  [16, 1,
                   0, 0,
                   0, 0,
                   0, 0,
                   0, 0,
                   0, 0,
                   0, 0,
                   0, 0,
                   1]
