model:
  name: q_multifc0
  transpile_before_run: True
  arch:
    down_sample_kernel_size: 6
    n_nodes: 4
    node_archs:
      - n_wires: 4
        encoder_op_list_name: 4x4_ryzxy
        n_blocks: 1
        q_layer_name: cxrzsx_0
      - n_wires: 4
        encoder_op_list_name: 4_ry
        n_blocks: 1
        q_layer_name: cxrzsx_0
      - n_wires: 4
        encoder_op_list_name: 4_ry
        n_blocks: 1
        q_layer_name: cxrzsx_0
      - n_wires: 4
        encoder_op_list_name: 4_ry
        n_blocks: 1
        q_layer_name: cxrzsx_0

qiskit:
  noise_model_name: ibmqx2
  optimization_level: 2
  initial_layout: [0, 1, 2, 3]
  transpile_with_ancilla: False
