model:
  arch:
    sample_arch: [2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1,
                  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                  1]
