model:
  name: super_qfc0
  arch:
    down_sample_kernel_size: 6
    encoder_op_list_name: 4x4_ryzxy
    n_layers_per_block: 2
    q_layer_name: u3cu3_s0

es:
  gene_mask: [-1, -1, -1, -1,
              4, 4,
              4, 4,
              4, 4,
              4, 4,
              4, 4,
              -1, -1,
              -1, -1,
              -1, -1,
              6]
