model:
  arch:
    sampling_method: gradient_based_sampling
    accumulation_window_size: 1
    sampling_ratio: 0.3
    sampling_window_size: 1

qiskit:
  use_qiskit_train: False
  use_qiskit_valid: False
  backend_name: ibmq_lima
  noise_model_name: ibmq_lima
            