model:
  arch:
    sample_arch:  [16, 2,
                   0, 0,
                   0, 0,
                   0, 0,
                   0, 0,
                   0, 0,
                   0, 0,
                   0, 0,
                   1]
