trainer:
  name: super_q_trainer

callbacks:
  - callback: 'SubnetInferenceRunner'
    split: 'valid'
    subnet: 'smallest'
    subcallbacks:
      - metrics: 'MinError'
        name: 'loss/smallest_valid'
  - callback: 'SubnetInferenceRunner'
    split: 'valid'
    subnet: 'middle'
    subcallbacks:
      - metrics: 'MinError'
        name: 'loss/middle_valid'
  - callback: 'SubnetInferenceRunner'
    split: 'valid'
    subnet: 'largest'
    subcallbacks:
      - metrics: 'MinError'
        name: 'loss/largest_valid'
  - callback: 'SubnetInferenceRunner'
    split: 'test'
    subnet: 'smallest'
    subcallbacks:
      - metrics: 'MinError'
        name: 'loss/smallest_test'
  - callback: 'SubnetInferenceRunner'
    split: 'test'
    subnet: 'middle'
    subcallbacks:
      - metrics: 'MinError'
        name: 'loss/middle_test'
  - callback: 'SubnetInferenceRunner'
    split: 'test'
    subnet: 'largest'
    subcallbacks:
      - metrics: 'MinError'
        name: 'loss/largest_test'
  - callback: 'MinSaver'
    name: 'loss/largest_valid'
  - callback: 'Saver'
    max_to_keep: 10
