model:
  arch:
    sampling_method: gradient_based_deterministic
    accumulation_window_size: 1
    sampling_ratio: 0.5
    sampling_window_size: 2

qiskit:
  use_qiskit_train: True
  use_qiskit_valid: True
