model:
  arch:
    n_nodes: 2
    node_archs:
      - n_wires: 2
        encoder_op_list_name: 1x1_ry
        n_blocks: 1
        n_layers_per_block: 2
        q_layer_name: ryrycx
      - n_wires: 2
        encoder_op_list_name: 2x1_ryry
        n_blocks: 1
        n_layers_per_block: 2
        q_layer_name: ryrycx


qiskit:
  use_qiskit_train: False
  use_qiskit_valid: False
  backend_name: ibmq_lima
  noise_model_name: ibmq_lima
