model:
  arch:
    n_blocks: 1
    n_front_share_blocks: 1
    n_front_share_wires: 1
    n_front_share_ops: 1
  sampler:
    strategy:
      n_diffs: 7

run:
  bsz: 2
  n_warm_epochs: 15
  n_epochs: 100

dataset:
  center_crop: 25
