model:
  name: q_fc12
  arch:
    n_blocks: 4
  load_op_list: False
  transpile_before_run: True

qiskit:
  use_qiskit: False
  use_real_qc: False
  backend_name: null
  noise_model_name: ibmq_lima
  coupling_map_name: ibmq_lima
  basis_gates_name: ibmq_lima
  initial_layout: [ 0, 1, 2, 3 ]
  optimization_level: 0
