model:
  name: q_fc12
  arch:
    n_blocks: 4

qiskit:
  use_qiskit: True
  use_real_qc: False
  backend_name: ibmq_santiago
  noise_model_name: ibmq_santiago
  coupling_map_name: ibmq_santiago
  basis_gates_name: ibmq_santiago
  initial_layout: [0, 1, 2, 3]
  optimization_level: 3
