es:
  gene_mask: [-1, -1, -1, -1,
              4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 0, 0, 0, 0, 0, 0,
              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4 ]

model:
  name: super_qfc0
  arch:
    down_sample_kernel_size: 6
    encoder_op_list_name: 4x4_ryzxy
    n_layers_per_block: 4
    q_layer_name: barren_s0

