trainer:
  name: q_noise_aware_trainer
  add_noise: True
  ignored_noise_ops: ['id', 'kraus', 'reset']

model:
  transpile_before_run: True


callbacks:
  - callback: 'AddNoiseInferenceRunner'
    split: 'valid'
    noise_total_prob: 0.01
    subcallbacks:
      - metrics: 'CategoricalAccuracy'
        name: 'acc/noi0.01_valid'
      - metrics: 'NLLError'
        name: 'loss/noi0.01_valid'
  - callback: 'AddNoiseInferenceRunner'
    split: 'valid'
    noise_total_prob: 0.02
    subcallbacks:
      - metrics: 'CategoricalAccuracy'
        name: 'acc/noi0.02_valid'
      - metrics: 'NLLError'
        name: 'loss/noi0.02_valid'
  - callback: 'AddNoiseInferenceRunner'
    split: 'valid'
    noise_total_prob: 0.05
    subcallbacks:
      - metrics: 'CategoricalAccuracy'
        name: 'acc/noi0.05_valid'
      - metrics: 'NLLError'
        name: 'loss/noi0.05_valid'
  - callback: 'AddNoiseInferenceRunner'
    split: 'valid'
    noise_total_prob: 0.1
    subcallbacks:
      - metrics: 'CategoricalAccuracy'
        name: 'acc/noi0.1_valid'
      - metrics: 'NLLError'
        name: 'loss/noi0.1_valid'
  - callback: 'AddNoiseInferenceRunner'
    split: 'valid'
    noise_total_prob: 0.2
    subcallbacks:
      - metrics: 'CategoricalAccuracy'
        name: 'acc/noi0.2_valid'
      - metrics: 'NLLError'
        name: 'loss/noi0.2_valid'
  - callback: 'AddNoiseInferenceRunner'
    split: 'valid'
    noise_total_prob: 0.5
    subcallbacks:
      - metrics: 'CategoricalAccuracy'
        name: 'acc/noi0.5_valid'
      - metrics: 'NLLError'
        name: 'loss/noi0.5_valid'
  - callback: 'AddNoiseInferenceRunner'
    split: 'test'
    noise_total_prob: 0.01
    subcallbacks:
      - metrics: 'CategoricalAccuracy'
        name: 'acc/noi0.01_test'
      - metrics: 'NLLError'
        name: 'loss/noi0.01_test'
  - callback: 'AddNoiseInferenceRunner'
    split: 'test'
    noise_total_prob: 0.02
    subcallbacks:
      - metrics: 'CategoricalAccuracy'
        name: 'acc/noi0.02_test'
      - metrics: 'NLLError'
        name: 'loss/noi0.02_test'
  - callback: 'AddNoiseInferenceRunner'
    split: 'test'
    noise_total_prob: 0.05
    subcallbacks:
      - metrics: 'CategoricalAccuracy'
        name: 'acc/noi0.05_test'
      - metrics: 'NLLError'
        name: 'loss/noi0.05_test'
  - callback: 'AddNoiseInferenceRunner'
    split: 'test'
    noise_total_prob: 0.1
    subcallbacks:
      - metrics: 'CategoricalAccuracy'
        name: 'acc/noi0.1_test'
      - metrics: 'NLLError'
        name: 'loss/noi0.1_test'
  - callback: 'AddNoiseInferenceRunner'
    split: 'test'
    noise_total_prob: 0.2
    subcallbacks:
      - metrics: 'CategoricalAccuracy'
        name: 'acc/noi0.2_test'
      - metrics: 'NLLError'
        name: 'loss/noi0.2_test'
  - callback: 'AddNoiseInferenceRunner'
    split: 'test'
    noise_total_prob: 0.5
    subcallbacks:
      - metrics: 'CategoricalAccuracy'
        name: 'acc/noi0.5_test'
      - metrics: 'NLLError'
        name: 'loss/noi0.5_test'
  - callback: 'InferenceRunner'
    split: 'valid'
    subcallbacks:
      - metrics: 'CategoricalAccuracy'
        name: 'acc/valid'
      - metrics: 'NLLError'
        name: 'loss/valid'
  - callback: 'InferenceRunner'
    split: 'test'
    subcallbacks:
      - metrics: 'CategoricalAccuracy'
        name: 'acc/test'
      - metrics: 'NLLError'
        name: 'loss/test'
  - callback: 'MaxSaver'
    name: 'acc/valid'
  - callback: 'Saver'
    max_to_keep: 10
