model:
  transpile_before_run: False
  load_op_list: False
  name: vqe_0
  hamil_filename: './examples/data/vqe/h2/h2.txt'
  arch:
    n_wires: 4
    op_type_name: [ 'u3', 'cu3' ]
    n_random_ops: null
    n_random_params: 180
