model:
  arch:
    n_nodes: 1
    node_archs:
      - n_wires: 4
        encoder_op_list_name: 4x4_ryzxy
        n_blocks: 1
        n_layers_per_block: 2
        q_layer_name: seth_0


qiskit:
  use_qiskit_train: False
  use_qiskit_valid: False
  backend_name: ibmq_jakarta
  noise_model_name: ibmq_jakarta
