model:
  name: super_qfc5
  arch:
    down_sample_kernel_size: 4
    encoder_op_list_name: 6x6_ryrzrx
    n_layers_per_block: 2
    q_layer_name: u3cu3_s0
    n_wires: 16
    output_remain: 10
    output_len: 10

