qiskit:
  use_qiskit: False
  use_real_qc: False
  backend_name: null
  noise_model_name: null
  coupling_map_name: null
  basis_gates_name: null
  n_shots: 8192
  initial_layout: null
  seed_transpiler: 42
  seed_simulator: 42
  optimization_level: null

dataset:
  n_test_samples: null

es:
  population_size: 10
  parent_size: 4
  mutation_size: 3
  mutation_prob: 0.3
  crossover_size: 3
  n_iterations: 40

ckpt:
  load_ckpt: True
