model:
  name: super_qfc4

qiskit:
  use_qiskit: False
  use_real_qc: False
  backend_name: ibmq_lima
  noise_model_name: ibmq_lima
  coupling_map_name: ibmq_lima
  basis_gates_name: ibmq_lima
  n_shots: 8192
  initial_layout: [0, 1, 2, 3]
  seed_transpiler: 42
  seed_simulator: 42
  optimization_level: 0

dataset:
  n_test_samples: null

es:
  population_size: 10
  parent_size: 4
  mutation_size: 3
  mutation_prob: 0.3
  crossover_size: 3
  n_iterations: 1
  est_success_rate: True
  eval:
    use_noise_model: True
    use_real_qc: True
    bsz: qiskit_max
    n_test_samples: 75

ckpt:
  name: 'checkpoints/step-9000.pt'
