model:
  arch:
    sample_arch: [4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 1,
                  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                  1]
