trainer:
  name: super_q_trainer

callbacks:
  - callback: 'SubnetInferenceRunner'
    split: 'valid'
    subnet: 'smallest'
    subcallbacks:
      - metrics: 'CategoricalAccuracy'
        name: 'acc/smallest_valid'
  - callback: 'SubnetInferenceRunner'
    split: 'valid'
    subnet: 'middle'
    subcallbacks:
      - metrics: 'CategoricalAccuracy'
        name: 'acc/middle_valid'
  - callback: 'SubnetInferenceRunner'
    split: 'valid'
    subnet: 'largest'
    subcallbacks:
      - metrics: 'CategoricalAccuracy'
        name: 'acc/largest_valid'
  - callback: 'SubnetInferenceRunner'
    split: 'test'
    subnet: 'smallest'
    subcallbacks:
      - metrics: 'CategoricalAccuracy'
        name: 'acc/smallest_test'
  - callback: 'SubnetInferenceRunner'
    split: 'test'
    subnet: 'middle'
    subcallbacks:
      - metrics: 'CategoricalAccuracy'
        name: 'acc/middle_test'
  - callback: 'SubnetInferenceRunner'
    split: 'test'
    subnet: 'largest'
    subcallbacks:
      - metrics: 'CategoricalAccuracy'
        name: 'acc/largest_test'
  - callback: 'MaxSaver'
    name: 'acc/largest_valid'
