dataset:
  name: mnist
  root: 'examples/data'
  train_valid_split_ratio: [0.9, 0.1]

run:
  n_epochs: 100
  bsz: 64
  workers_per_gpu: 8
  device: gpu

debug:
  pdb: False
  set_seed: True
  seed: 42
