model:
  name: supervqe_0
  arch:
    n_layers_per_block: 11
    q_layer_name: maxwell_s0

scheduler:
  name: cosine_warm

run:
  n_warm_epochs: 15

callbacks:
  - callback: 'SubnetInferenceRunner'
    split: 'valid'
    subnet: 'smallest'
    subcallbacks:
      - metrics: 'MinError'
        name: 'superloss/smallest_valid'
  - callback: 'SubnetInferenceRunner'
    split: 'valid'
    subnet: 'middle'
    subcallbacks:
      - metrics: 'MinError'
        name: 'superloss/middle_valid'
  - callback: 'SubnetInferenceRunner'
    split: 'valid'
    subnet: 'largest'
    subcallbacks:
      - metrics: 'MinError'
        name: 'superloss/largest_valid'
  - callback: 'MinSaver'
    name: 'superloss/largest_valid'
  - callback: 'Saver'
    max_to_keep: 10
