qiskit:
  use_qiskit: False
  use_real_qc: False
  backend_name: null
  noise_model_name: null
  coupling_map_name: null
  basis_gates_name: null
  n_shots: 8192
  initial_layout: null
  seed_transpiler: 42
  seed_simulator: 42
  optimization_level: 0

dataset:
  n_test_samples: null

run:
  bsz: 900

ckpt:
  load_ckpt: True
  load_trainer: False
  name: 'checkpoints/max-acc-valid.pt'

model:
  load_op_list: False
  transpile_before_run: False

prune:
  eval:
    remove_ops: False
    remove_ops_thres: 1e-5
