qiskit:
  use_qiskit: False
  use_real_qc: False
  backend_name: null
  noise_model_name: null
  coupling_map_name: null
  basis_gates_name: null
  n_shots: 8192
  initial_layout: null
  seed_transpiler: 42
  seed_simulator: 42
  optimization_level: null

dataset:
  n_test_samples: null

legalize_unitary: True

run:
  bsz: 900

ckpt:
  name: 'checkpoints/max-acc-valid.pt'
