model:
  arch:
    n_nodes: 1
    node_archs:
      - n_wires: 8
        encoder_op_list_name: 8x2_ryz
        n_blocks: 1
        n_layers_per_block: 2
        q_layer_name: seth_0

qiskit:
  use_qiskit_train: True
  use_qiskit_valid: True
  backend_name: ibmq_guadalupe
  noise_model_name: ibmq_guadalupe
