dataset:
  digits_of_interest: [3, 6]
  front_size: 500

model:
  transpile_before_run: False
  load_op_list: False
  arch:
    n_wires: 8
    output_len: 4


run:
  n_epochs: 5
  n_warm_epochs: 0
  bsz: 50
  eval_bsz: 75
  workers_per_gpu: 8
  device: gpu