model:
  arch:
    n_nodes: 2
    node_archs:
      - n_wires: 2
        encoder_op_list_name: 1x1_ry
        n_blocks: 1
        n_layers_per_block: 2
        q_layer_name: ryrycx
      - n_wires: 2
        encoder_op_list_name: 2x1_ryry
        n_blocks: 1
        n_layers_per_block: 2
        q_layer_name: ryrycx

trainer:
  act_quant: False

qiskit:
  use_qiskit_train: True
  use_qiskit_valid: True
  backend_name: ibmq_bogota
  noise_model_name: ibmq_bogota
