model:
  name: super_qfc5
  arch:
    down_sample_kernel_size: 5
    encoder_op_list_name: 25_ryrz
    n_layers_per_block: 2
    q_layer_name: u3cu3_s0
    n_wires: 21
    output_remain: 20
    output_len: 4

