model:
  arch:
    n_nodes: 1
    node_archs:
      - n_wires: 16
        encoder_op_list_name: 16x1_ry
        n_blocks: 3
        n_layers_per_block: 2
        q_layer_name: seth_0

qiskit:
  use_qiskit_train: True
  use_qiskit_valid: True
  backend_name: ibmq_toronto
  noise_model_name: ibmq_toronto
