trainer:
  noise_total_prob: null
  act_quant: True
  act_quant_level: 6
  act_quant_ratio: 1
  act_quant_skip_last_node: True
  act_quant_loss: True
  act_quant_loss_lambda: 0.1

model:
  arch:
    n_nodes: 2
    node_archs:
      - n_wires: 4
        encoder_op_list_name: 4x4_ryzxy
        n_blocks: 1
        n_layers_per_block: 2
        q_layer_name: u3cu3_0
        act_norm: layer_norm
      - n_wires: 4
        encoder_op_list_name: 4_ry
        n_blocks: 1
        n_layers_per_block: 2
        q_layer_name: u3cu3_0
        act_norm: layer_norm

