model:
  arch:
    n_blocks: 2
  transpile_before_run: True

qiskit:
  use_qiskit: False
  use_real_qc: False
  backend_name: ibmqx2
  noise_model_name: ibmqx2
  optimization_level: 2

trainer:
  add_noise: True
