dataset:
  name: layer_regression
  root: 'examples/data'
  train_valid_split_ratio: [0.9, 0.1]

criterion:
  name: mse

optimizer:
  name: adam
  lr: 1e-1
  weight_decay: 0.0

scheduler:
  name: constant

run:
  n_epochs: 100
  bsz: 1
  workers_per_gpu: 8
  device: gpu

debug:
  pdb: False
  set_seed: True
  seed: 42
