trainer:
  act_quant: True
  act_quant_bit: null
  act_quant_level: 3
  act_quant_ratio: 1

trainer:
  noise_total_prob: 0.1
  act_quant: True
  act_quant_level: 3
  act_quant_ratio: 1
  act_quant_skip_last_node: True
  act_quant_loss: True
  act_quant_loss_lambda: 10