model:
  name: super_qfc0
  arch:
    down_sample_kernel_size: 6
    encoder_op_list_name: 4x4_ryzxy
    n_layers_per_block: 2
    q_layer_name: u3cu3_a0

scheduler:
  name: cosine_warm

run:
  n_warm_epochs: 30

callbacks:
  - callback: 'SubnetInferenceRunner'
    split: 'valid'
    subnet: 'smallest'
    subcallbacks:
      - metrics: 'CategoricalAccuracy'
        name: 'superacc/smallest_valid'
      - metrics: 'NLLError'
        name: 'superloss/smallest_valid'
  - callback: 'SubnetInferenceRunner'
    split: 'valid'
    subnet: 'middle'
    subcallbacks:
      - metrics: 'CategoricalAccuracy'
        name: 'superacc/middle_valid'
      - metrics: 'NLLError'
        name: 'superloss/middle_valid'
  - callback: 'SubnetInferenceRunner'
    split: 'valid'
    subnet: 'largest'
    subcallbacks:
      - metrics: 'CategoricalAccuracy'
        name: 'superacc/largest_valid'
      - metrics: 'NLLError'
        name: 'superloss/largest_valid'
  - callback: 'MaxSaver'
    name: 'superacc/largest_valid'
  - callback: 'Saver'
    max_to_keep: 10
