model:
  arch:
    sample_arch:  [21, 0,
                   0, 0,
                   0, 0,
                   0, 0,
                   0, 0,
                   0, 0,
                   0, 0,
                   0, 0,
                   1]
